### ISSUE TITLE
Is it possible to use this without Google API key?

### ISSUE THREAD

**Issue by Niesyto** [rameshsyn/react-location-picker#21]
I don't know if I'm doing something wrong, but the map doesn't load. Probably becouse I don't have an API key. Is it possible to use this without one?

**Comment by rameshsyn** [comment]
@Niesyto No. Must include the API Key.

`<script src="https://maps.googleapis.com/maps/api/js?key=<INSERT_API_KEY_HERE>&v=3.exp&libraries=geometry,drawing,places"></script>`
